[tox]
minversion = 4.0
envlist = py38,py39,py310,py311,py312,py313,lint,docs

[testenv]
package = wheel
wheel_build_env = .pkg
deps = .[test]
commands =
  pytest test --verbosity=3 {posargs}

[testenv:lint]
deps =
  flake8
commands =
  flake8 {posargs} ncclient test

[testenv:docs]
deps = .[docs]
commands =
  sphinx-build -b html docs/source docs/html

[flake8]
show-source = True
ignore = E713
exclude = .venv,.git,.tox,dist,doc,.ropeproject
